### ISSUE TITLE
No Labeling after refresh a page

### ISSUE THREAD

**Issue by elfomaniac** [livecomposer/live-composer-page-builder#150]
This issue stable reproduced in google chrome (Mac and Windows). 
1. Open Edit in Live Composer
2.Click to edit orange block
3. Refresh page
4. Click to edit the same block again. 
5. No labeling.
http://prntscr.com/c69abp

**Comment by NGorco** [comment]
Hello! 

That's happening when some resource loading too long or slowing down page render. Some *.js from cdn etc. Provide Network screencast. 

Check network & resources panel in Chrome Debug Tool.

**Comment by elfomaniac** [comment]
Looks like a Smart slider 3 loads too long. After resize a window all labeling appear. 

http://prntscr.com/c6dtx0

**Comment by elfomaniac** [comment]
P.P.S. Last upate 1.0.9.43 + last WP 4,6 - not reproduced.
