### ISSUE TITLE
The LC templates section is not scrollable anymore

### ISSUE THREAD

**Issue by FoldingTheme** [livecomposer/live-composer-page-builder#170]
Hi there,

On last 1.1.2 version, I cannot access the saved templates if is needed to use the navigation.

https://www.evernote.com/l/AjMk7mCDzM9G3KRtdwrj1ajbR_wHeE0-8uIB/image.png

Thanks.

**Comment by NGorco** [comment]
Done with https://github.com/livecomposer/live-composer-page-builder/tree/issue/170
