### ISSUE TITLE
Accordion Element Title cannot be changed

### ISSUE THREAD

**Issue by Christian-Seiler** [livecomposer/live-composer-page-builder#172]
The Accordion Element Title cannot be changed

**Comment by livecomposer** [comment]
@Christian-Seiler do you have latest version 1.1.2 installed?
I have no such issue on my end.

**Comment by Christian-Seiler** [comment]
Yes, I do have the 1.1.2 Version.

**Comment by livecomposer** [comment]
- Do you have any JS errors?
- Can you please record a short video for me?

**Comment by Christian-Seiler** [comment]
I didn't get any errors
Video is here: https://vimeo.com/179240366

**Comment by Christian-Seiler** [comment]
It seems to be an issue related to Safari (Mac). I can edit the Title entries on Firefox (Mac) and IE (Win).

**Comment by livecomposer** [comment]
Thanks for your help with it. Comment stating that this bug is Safari helped a lot.
