### ISSUE TITLE
Text formatting on BLANK Theme not work.

### ISSUE THREAD

**Issue by elfomaniac** [livecomposer/live-composer-page-builder#177]
Create new post with a text wrapping a picture. It works on editor, But it does not on a page,
http://prntscr.com/c7512z

**Comment by livecomposer** [comment]
It's not a page builder problem but the theme issue. In any case I added a few class that every theme should have into the Live Composer. Can you please check the latest version available on GitHub?

**Comment by elfomaniac** [comment]
The text position changed. But the size of font did not changed.

**Comment by elfomaniac** [comment]
With blog template the same.
![blog_edit](https://cloud.githubusercontent.com/assets/9195541/17773327/db529722-651b-11e6-9a04-69d1277c2cd1.png)
![blog_page](https://cloud.githubusercontent.com/assets/9195541/17773330/dfac0f60-651b-11e6-8dca-067c26a04ff3.png)

**Comment by elfomaniac** [comment]
Now it works for me.

**Comment by livecomposer** [comment]
#186
