### ISSUE TITLE
Link POP OVER covering the field

### ISSUE THREAD

**Issue by tbenci** [livecomposer/live-composer-page-builder#178]
Since the 1.1 update the link POP OVER is not positioning correctly. Most commonly it is opening over the link itself.

![lc_error](https://cloud.githubusercontent.com/assets/7336557/17764037/0ddadd46-6560-11e6-8a08-2f2816542e2e.png)

**Comment by tbenci** [comment]
How do I role this back folks... need to undo this until it's fixed.

**Comment by livecomposer** [comment]
Thanks for reporting this.

Here you can download any version of LC: https://en-ca.wordpress.org/plugins/live-composer-page-builder/developers/

**Comment by tbenci** [comment]
Fantastic... fixed without any fuss... Thank you very much.

I am telling everyone about LC... I love the click and edit for links in this version you blokes are doing a great job.

**Comment by livecomposer** [comment]
Thank you for helping us.
