### ISSUE TITLE
Features Control

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#182]
When I choose a disabled the module is showing.  I recorded [a short video](https://drive.google.com/file/d/0B7nJlmCX4yHuWk1aUlJvcmxBdFE/view) for you.

**Comment by lukeperrie** [comment]
upvote....please fix! I am having the same exact issue. It's not a plugin conflict because I just disabled all the plugins on my site besides LC and it's still happening. Exactly the same as issue as you see in the video that @xdima92x recorded above. Thank you.

**Comment by livecomposer** [comment]
@lukeperrie can you please download and try the latest code update? https://github.com/livecomposer/live-composer-page-builder/archive/master.zip

I think it's solved, but want an second pair of eyes.

**Comment by lukeperrie** [comment]
@livecomposer will do - thank you for the quick response!

**Comment by lukeperrie** [comment]
Hey @livecomposer - I am still having an issue getting the Slider (Revolution) module to show on one of my sites in a multi site network - but not the other. See video here: https://cl.ly/h72R

Also - where did the option to order the modules alphabetically go? Please tell me you didn't wipe it?
