### ISSUE TITLE
LC: Add Modules Row - Error

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#196]
I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuanBac0NWaGxlX3M/view

**Comment by livecomposer** [comment]
Uncaught Error: cannot call methods on sortable prior to initialization; attempted to call method 'option'
File "http://domain.com/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,plupload&ver=4.6", line 2, char 1808

**Comment by livecomposer** [comment]
@NGorco I need you to check the pushed above commit. It solves the bug, but need a second look from you.

**Comment by xdima92x** [comment]
@livecomposer I again tested. It's work.

**Comment by NGorco** [comment]
Checked the code. 
Removed comments, it leaves sortable active while dragging. 
-----------------------

https://github.com/livecomposer/live-composer-page-builder/commit/6ff2d9abb51758f9a8e4ae63ef316c58de62a6aa
