### ISSUE TITLE
LC: InfoBox

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#199]
The nofollow does not work. https://www.evernote.com/shard/s554/sh/c60963e9-3d0d-44d6-8bd5-d867260941ef/90d9f210a2c90750

**Comment by livecomposer** [comment]
@xdima92x please fix it yourself.

**Comment by xdima92x** [comment]
@livecomposer please check - https://github.com/livecomposer/live-composer-page-builder/commits/issue/199
