### ISSUE TITLE
Drag and drop module issue

### ISSUE THREAD

**Issue by FoldingTheme** [livecomposer/live-composer-page-builder#207]
Hi there,

Please check the screencast attached. If you drag a module over module area and change your mind, the LC dragging options is freezing.

Cheers!

[LC-dropping-module-issue.mp4.zip](https://github.com/livecomposer/live-composer-page-builder/files/426754/LC-dropping-module-issue.mp4.zip)

**Comment by livecomposer** [comment]
Also click on module in modules listing breaks drag and drop.

**Comment by NGorco** [comment]
Fixed freezing scroll when dragging module away from list and backward.

**Comment by NGorco** [comment]
https://github.com/livecomposer/live-composer-page-builder/commit/82cb7a64c000ad36c0d8698ed1510da7d0aff64b
