### ISSUE TITLE
LC: Module The Content ( Tablet and Phone )

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#208]
The font size, line height, tex-align ( content ) does not wok in a tablet and phone. https://www.evernote.com/shard/s554/sh/9a03bbfb-3fe3-4653-a3c4-a8ed18774421/63a99540e290daa0

**Comment by livecomposer** [comment]
@xdima92x  can't reproduce it.
Please test it again with latest code update.

Thank you.
