### ISSUE TITLE
Page Titles Lost When LC is active

### ISSUE THREAD

**Issue by zutigrm** [livecomposer/live-composer-page-builder#214]
Hi,

Thanks for the latest update, I see you enchanted the UI and responsive mode is totally awesome!

When Live Composer is active, it affect titles (like &lt;title&gt; of the page), so in the browser tab I can see the current link instead of it's title http://screencast.com/t/3BYihogR4Cp

Great Work, this plugins so far is the best one available, totally easy to use and native UI makes it almost perfect !

**Comment by tristanleboss** [comment]
Same here. I traced the problem down to the "dslc_editing_screen_title" function which is applied by this plugin as a filter of the page title ("admin_title").

**Comment by tristanleboss** [comment]
function dslc_editing_screen_title($title) {
		$screen = get_current_screen();
	
		if ( 'toplevel_page_livecomposer_editor' !== $screen->id || ! isset( $_GET['page_id'] ) ) {
			return $title;
		}
	
		$title = 'Edit: ' . get_the_title( intval( $_GET['page_id'] ) );
		return $title;
	}

Because it's a filter, you need to accept an argument (the title) and return it... even if you don't touch it.

**Comment by livecomposer** [comment]
Thanks @tristanleboss for the fix.
(Next plugin update will include this patch)

**Comment by shalintj** [comment]
Is this fixed? I'm still facing an issue with this...

**Comment by christopher-maxwell** [comment]
I just started using LC yesterday and am experiencing the same issue.
