### ISSUE TITLE
update_option called on every page  is not good for caching plugin

### ISSUE THREAD

**Issue by tristanleboss** [livecomposer/live-composer-page-builder#215]
Your plugin is making a call to the WordPress function `update_option` on every page load. The call happens in the function `DSLC_Upgrade::init`.

It's not good because caching plugin like W3 Total Cache cache all queries but they have to flush the cache for a specific table when an UPDATE or INSERT statement is done on it. Because the `update_option` is doing a query on the `wp_options` table to either update or insert the option, the cache is flushed on every page load... disabling any benefits.

In your code, the `update_option` should only be called if `$curr_version` is changed which should be the case only one time after an upgrade.

	public static function init() {

		$curr_version_db = get_option( 'dslc_version' );

		if ( ! is_array( $curr_version_db ) ) {

			$curr_version = array();
		}
		else {

			$curr_version = $curr_version_db;
		}

		/** Migration usage example

		if ( ! in_array( '1', $curr_version ) ) {

			self::update_1();
			$curr_version[] = 1;
		}

		if ( ! in_array( '1.3', $curr_version ) ) {

			self::update_1_3();
			$curr_version[] = '1.3';
		}*/

		if ( ! in_array( DS_LIVE_COMPOSER_VER, $curr_version ) ) {

			$curr_version[] = DS_LIVE_COMPOSER_VER;
		}

		$curr_version = sort( $curr_version );

		if( $curr_version != $curr_version_db ) {

			// Updated ro current version.
			update_option( 'dslc_version', $curr_version );
		}
	}

**Comment by livecomposer** [comment]
Good point sorry for this issue.
