### ISSUE TITLE
LC: Module Woo - Errors

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#225]
1) The title doesn't work a font size and line height in Tablet and Phone. https://www.evernote.com/shard/s554/sh/5f4300c6-437f-4919-ba1e-723851e21bf3/f14530f68a17117d
2) Price -> Position doesn't work. https://www.evernote.com/shard/s554/sh/5655ab58-b5cd-4798-b6e1-3a26faad3762/7391b5408c9598a1

**Comment by carlsdesign** [comment]
Link?

**Comment by xdima92x** [comment]
yes

**Comment by livecomposer** [comment]
@carlsdesign  what wrong with link in WooCommerce module?

**Comment by livecomposer** [comment]
@xdima92x Commit #235 wasn't good. Please, check the bugs your found against code in this branch: https://github.com/livecomposer/live-composer-page-builder/tree/issue/225_ver2

Thank you.

**Comment by xdima92x** [comment]
@livecomposer I checked. It works.
