### ISSUE TITLE
LC: Module Galleries - Error

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#226]
Count -> Position doesn't work. https://www.evernote.com/shard/s554/sh/c08b6380-3639-44cc-b838-6fe7f8f9647a/79cbc968deca41e3

**Comment by xdima92x** [comment]
@lumberman please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/226

**Comment by livecomposer** [comment]
@xdima92x Please check how it's done in post based modules or in WooCommerce module.

dslc-init-center
dslc-init-target

Try to apply the same approach to the gallery. Create a new branch /issue/226_ver2

**Comment by xdima92x** [comment]
@lumberman please check - https://github.com/livecomposer/live-composer-page-builder/commits/issue/226
