### ISSUE TITLE
Info text not render HTML tags

### ISSUE THREAD

**Issue by FoldingTheme** [livecomposer/live-composer-page-builder#231]
Hi there,

Is talking about <strong> and <br> tags which are visible in text. Not a big deal, but thought you want to know about that.

https://www.evernote.com/l/AjPeBBMtk_JHgonfM-38RFZtHKhvwReOc8YB/image.png

Cheers!

**Comment by xdima92x** [comment]
@lumberman please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/231
