### ISSUE TITLE
LC: Module Downloads - Main -> Location 

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#233]
Styling -> Main -> Location ( Inside Thumbnail ( hower ) and Inside Thumbnail ( always visible ) ) not working properly. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuY0FjV3IzMjhwZjg/view

**Comment by xdima92x** [comment]
@lumberman done

**Comment by livecomposer** [comment]
#236
