### ISSUE TITLE
Inactive Tab Background Color

### ISSUE THREAD

**Issue by ElementalCrisis** [livecomposer/live-composer-page-builder#245]
When disabling the background color for inactive tabs, it automatically applies the default background color.

**Comment by ElementalCrisis** [comment]
An update, it seems disabling any setting has it revert to it's default settings.

**Comment by livecomposer** [comment]
Disabling styling feature remove inline CSS for this feature. Every module has some basic/default setting for elements. You can override default CSS in your theme or via custom CSS plugin.
