### ISSUE TITLE
Copy/Paste does not work in-line

### ISSUE THREAD

**Issue by lukeperrie** [livecomposer/live-composer-page-builder#249]
See video: https://cl.ly/hIvB

Copying and pasting in-line seems to remove all formatting from the text module until you cancel the changes, and then it goes back.

**Comment by lukeperrie** [comment]
Any updates on this?

**Comment by livecomposer** [comment]
@NGorco Please check this issue.

**Comment by lukeperrie** [comment]
Is this supposed to be fixed? Not fixed for me.

**Comment by livecomposer** [comment]
Please check now the maser branch.

**Comment by lukeperrie** [comment]
Perfect - thank you!
