### ISSUE TITLE
"Fixed" Menu option - content goes BEHIND the menu when at the top of the page

### ISSUE THREAD

**Issue by lukeperrie** [livecomposer/live-composer-page-builder#250]
Please see screenshot: https://cl.ly/hJOl

And video: https://cl.ly/hJRO

The "Fixed" menu option is used to get the "sticky" menu effect, where the menu stays with you as you scroll. This works great, except for the fact that when you are at the very top of the page, it lays the menu ON TOP OF the content, just like the Absolute option.

This is incorrect. User-expected behavior for a sticky menu would be for it to be NOT on top of the content when at the very top of the page, and only overlay the content once you scroll. As you can see - it messes things up royally when you are using a header image, etc.

Please let me know when this can be fixed. I cannot use the "Fixed" menu option on any sites until it's fixed.

**Comment by lukeperrie** [comment]
Any updates on this?

**Comment by livecomposer** [comment]
Hey Luke,
Is it happening in the editing mode only? If so, it's not a bug but feature :) We disable absolute/fixed preview in the editing mode, so you can edit the first section without any issues. Fixed/absolute header effect will work in production mode or when you click on **Hide Editor** button. Please, see [this screenshot](https://www.evernote.com/l/AAFCEXCbjb9GHo6Oq9oIuXRJ4sILBwxmsmY).

Open this issue again if you have more questions or I'm wrong.

**Comment by lukeperrie** [comment]
@livecomposer  - please re-open this.

Please watch the video again very carefully. You will see that when Live Composer is deactivated, the content goes behind the menu. This is not just happening in editing mode. The content goes behind the menu when you deactivate the editor.

**Comment by lukeperrie** [comment]
Also - unless I'm missing it, I do not have the capability of opening the issue again. Pleas advise.
