### ISSUE TITLE
Space Being Added At End Of Table

### ISSUE THREAD

**Issue by ElementalCrisis** [livecomposer/live-composer-page-builder#251]
I've noticed that when I update a table or changed a textbox with a table, I had to manually go and remove ``&nbsp;`` from the bottom each time as it adds it when switching to visual.

**Comment by livecomposer** [comment]
Can you please post example of the text/code you have issues with?
Thank you.

**Comment by ElementalCrisis** [comment]
It's on my localhost but I'm able to replicate it with any table I add into a textbox.

**Comment by livecomposer** [comment]
Don't you have the same behavior in standard WP editor?

**Comment by ElementalCrisis** [comment]
I added a table in the normal WordPress page editor and it did not add `&nbsp;` at the bottom when I went back and updated it.

**Comment by xdima92x** [comment]
@ElementalCrisis Hi) I am not sure but please read this article - http://wordpress.stackexchange.com/questions/29702/wordpress-automatically-adding-nbsp

**Comment by ElementalCrisis** [comment]
Hello, 

Thanks for the link, that's probably the issue.
