### ISSUE TITLE
Padding Vertical Shows Differently in Editor Mode than in Live Mode

### ISSUE THREAD

**Issue by lukeperrie** [livecomposer/live-composer-page-builder#275]
Hey guys - please see screenshot and video below. I don't believe I saw this bug until after the major 1.1 update.

Often, after I adjust the Padding Vertical for a modules row, and then save, when I exit Editor mode, it looks different - which defeats the purpose of front end editing :-).

Video: https://cl.ly/hPwO

Screenshot showing what I DON'T see in Editor mode (only shows once it's saved and I have exited editor mode): https://cl.ly/hPx8

**Comment by xdima92x** [comment]
Hi @lukeperrie In the video do you use a module 'Text'? If yes, you can use an HTML tag h1 or h2. The inline editor for content [will be to add an HTML tag 'p' in the Editor Mode](https://www.evernote.com/shard/s554/sh/5f7219a3-5ee5-45d6-beda-2b47d7630efe/26f93f67dadf3825). Also, you can use [this option](https://www.evernote.com/shard/s554/sh/198d537f-e752-4fce-93d4-4d5ed936c3c9/5f0730799e664d48) that to delete a margin.

**Comment by xdima92x** [comment]
Hi @lumberman Please check, the inline editor for content [will be to add an HTML tag 'p' in the Editor Mode.](https://www.evernote.com/shard/s554/sh/5f7219a3-5ee5-45d6-beda-2b47d7630efe/26f93f67dadf3825)
