### ISSUE TITLE
Strange Accordion Behavior

### ISSUE THREAD

**Issue by ElementalCrisis** [livecomposer/live-composer-page-builder#288]
As you can see in the attached zipped video, when I attempt to edit the accordion it locks up the module and wont allow me to do anything forcing me to refresh the page.

[AccordionBehavior.zip](https://github.com/livecomposer/live-composer-page-builder/files/465312/AccordionBehavior.zip)

Also in the video you can see the space issue I talked about in https://github.com/livecomposer/live-composer-page-builder/issues/251.

**Comment by xdima92x** [comment]
@ElementalCrisis Hi) 
1) Do you get an errror in the [Error Detected](https://livecomposerplugin.com/blog/live-composer-1-1-released/#js-error)?
2) Try do deactivate all the other plugins for a minute and see if LC works as expected? 
3) Try to activate a default WP theme for a minute and see if LC works as expected? 
4) Do you use the latest version LC? If not, please update
5) I can not re-create your bug. Can [you export a page](https://d33v4339jhl8k0.cloudfront.net/docs/assets/54d0dd69e4b034c37ea8ceda/images/5722aa61c69791092312f3d1/file-AipMB3oG2N.png) for me? https://livecomposer.help/article/167-how-to-save-and-reuse-the-page-design

**Comment by ElementalCrisis** [comment]
Hello,

I never received an error notice when it happened and I did try deactivating all plugins yet still had the error. Never tried the default WP theme though. As I'm unable to reproduce it on 1.1.4 maybe another fix inadvertently fixed this bug. I'll update this issue if I do encounter it again.
