### ISSUE TITLE
LC Archive Index Templates Still Active when deactivated

### ISSUE THREAD

**Issue by IsaacAdu** [livecomposer/live-composer-page-builder#293]
The archive templates are still active and take over archive display even after unchecked and deactivated from appearance >LC templates >Blog Posts. They remain active until the template is trashed and deleted; the default theme archive templates take over display on after LC's templates has been deleted.

**Comment by livecomposer** [comment]
Hi Isaac,

We fixed this problem in version 1.1.4. Can you please update your Live Composer to the latest version and let me know if you see this or any other bugs?

Thank you!
