### ISSUE TITLE
Social Button Disappear Since Update

### ISSUE THREAD

**Issue by Deanphillips** [livecomposer/live-composer-page-builder#299]
Hey guys,

The social buttons (being displayed by Easy Social Buttons) disappear at the bottom of a row, since the new update:

http://www.thesuperhumanlab.com/nutrition-guide-for-skinny-guys/

See that as an example 

I have to place the content module (and leave it empty) for these share buttons to display (as it goes off content)

**Comment by Deanphillips** [comment]
Did you guys see the problem?! 

Thanks

**Comment by xdima92x** [comment]
@Deanphillips Hi) Do you [mean it](https://www.evernote.com/shard/s554/sh/af4d151d-5931-4922-9141-ad7fa38ce16f/8503e1cef9bd933c) when scrolling the page? You [can add a class](https://www.evernote.com/shard/s554/sh/37a45f9f-c9e1-4c4e-9cc2-1828568f80d3/7fa633a8b25ae0be) for the content module and add the property 'z-index:999' in your CSS. You can use a plugin 'Custom CSS' for to add the custom CSS.

**Comment by Deanphillips** [comment]
I added a class, and put that css in, and it didn't change anything :)

**Comment by Deanphillips** [comment]
Yeah. 

I've added the custom class the content module "content guide"

Then I've put:

contentguide { 
z-index:999
}

I've also tried 'z-index:999' and z-index: 999 too

**Comment by xdima92x** [comment]
You can this:

.contentguide { 
z-index:999
}

You need to add a point before the custom class.

**Comment by Deanphillips** [comment]
That didn't do anything, neither :/

Weirdly.

**Comment by xdima92x** [comment]
Nothing, we need to fix this problem. :) Where you add CSS? plugin 'Custom CSS' or file - style.css in your theme? Can you use plugin 'Custom CSS'?

**Comment by Deanphillips** [comment]
Yep.

I have royal css installed to install things on a page basis, 

Just tested it with the Custom CSS plugin (site wide) and still nothing,

<img width="742" alt="screenshot 2016-09-19 18 34 13" src="https://cloud.githubusercontent.com/assets/21025321/18642244/d3b707ec-7e97-11e6-9b96-f01f82c0bf2c.png">
<img width="361" alt="screenshot 2016-09-19 18 34 19" src="https://cloud.githubusercontent.com/assets/21025321/18642245/d3f697e0-7e97-11e6-88be-34b581de0e57.png">
<img width="1017" alt="screenshot 2016-09-19 18 34 45" src="https://cloud.githubusercontent.com/assets/21025321/18642246/d3f9bb14-7e97-11e6-90a4-d3a0f500dd9e.png">

**Comment by Deanphillips** [comment]
Is this, and the random css added to the content module (see my other issue logged) related at all?

As both things weren't here until one the latest updates :)

**Comment by xdima92x** [comment]
ohhh.... I do know what to advise. Can you add CSS in your theme ( file - style.css )? Can you send me your temporary access details for your WordPress admin panel

**Comment by Deanphillips** [comment]
Yes of course! Where shall I sent you the temp login? :)

**Comment by xdima92x** [comment]
You can send here - dima92.mvs@gmail.com Tomorrow I will check :)

**Comment by xdima92x** [comment]
@Deanphillips Please check)

**Comment by Deanphillips** [comment]
All working!

Thank you so much :)

I'll remember to add that custom class going forward :)

Thanks so much

**Comment by xdima92x** [comment]
You are welcome)
