### ISSUE TITLE
content block appears 

### ISSUE THREAD

**Issue by Deanphillips** [livecomposer/live-composer-page-builder#313]
Hey guys,

Getting this funky box whenever I put the content tab in (I do this to have the social buttons display)

Thanks 

<img width="1437" alt="screenshot 2016-09-17 16 00 26" src="https://cloud.githubusercontent.com/assets/21025321/18609053/4febd986-7cf0-11e6-8b73-5c45f7a1f771.png">

**Comment by xdima92x** [comment]
Hi @Deanphillips :) I saw your site. It is a problem in your CSS. Please [check this screenshot](https://www.evernote.com/shard/s554/sh/55a63843-8803-4dc7-b2ee-38160b92ec48/8892acf4b1f2d409) for more details.

**Comment by Deanphillips** [comment]
I'm using an LC theme (so it's caused by LC) - how can I fix this? :)

**Comment by xdima92x** [comment]
@Deanphillips You have[ an id 'dslc-theme-content'](https://www.evernote.com/shard/s554/sh/40e0680c-5ebc-450b-b4f0-a5231b0a6131/be91c136f59713b3). You need to delete these properties or delete the id 'dslc-theme-content' in your module.

**Comment by xdima92x** [comment]
@Deanphillips Please check) You need to change your theme 'Josephine' ( style.css ) :)

**Comment by xdima92x** [comment]
@Deanphillips done? :)
