### ISSUE TITLE
[Question] How to use if the WordPress URL is different than the site

### ISSUE THREAD

**Issue by juan-manuel-alberro** [livecomposer/live-composer-page-builder#49]
Hello, 

I've a blog where my WordPress files are in a folder so my configuration is like

WordPress URL: https://mydomain.com/site
Site URL: https://mydomain.com

And I cannot use the plugin because it force me to use https://mydomain.com/site as site URL.
There's a way to fix that? Actually my blog works without enter to `/site`.

If I wasn't clear, [check this](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory#Moving_a_Root_install_to_its_own_directory).

Thanks.

**Comment by livecomposer** [comment]
New version should not rely on site URL but post ids.
Please test if you have such possibility.
