### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by szepeviktor** [livecomposer/live-composer-page-builder#98]
Good morning!

Please consider implementing **PHP class autoloader** as the big guys do.

ps. nice to have WPCS

**Comment by livecomposer** [comment]
Hi there,
Please see branch /feature/classes/ (work in progress). Feedback much appreciated.

**Comment by szepeviktor** [comment]
It is quite complicated to to make a proper WP plugin.
Are you interested in what/how to do?

**Comment by livecomposer** [comment]
We are recoding the plugin structure trying to get rid of global variables and compose plugin pieces into classes with a proper structure. If you are using LC and have experience in OOP patterns please feel free to help us with critique/review.

**Comment by szepeviktor** [comment]
I think the essentials are.

1. Use TravisCI
1. Don't commit to master, use PR-s passing Travis, no *Works for me*
1. Use https://github.com/xwp/wp-dev-lib

Is it OK for you?

**Comment by szepeviktor** [comment]
I assume it is a *no*.

**Comment by livecomposer** [comment]
@szepeviktor I closed ticket as I got your answer and can't add anything to the topic. 
We already use CI (not Travis) and our php/js code validates though phpcs inflight in SublimeText while we are writing it.

As for php OPP we are working on it, but it will take months to migrate. 

Your further advice or ideas are more than welcome!
